export const VERSION = '0.218.2'

export * as ascii85 from 'https://deno.land/std@0.218.2/encoding/ascii85.ts'
export * as base32 from 'https://deno.land/std@0.218.2/encoding/base32.ts'
export * as base58 from 'https://deno.land/std@0.218.2/encoding/base58.ts'
export * as base64 from 'https://deno.land/std@0.218.2/encoding/base64.ts'
export * as base64url from 'https://deno.land/std@0.218.2/encoding/base64url.ts'
export * as hex from 'https://deno.land/std@0.218.2/encoding/hex.ts'
export * as varint from 'https://deno.land/std@0.218.2/encoding/varint.ts'
export * as jsonc from 'https://deno.land/std@0.218.2/jsonc/mod.ts'
export * as msgpack from 'https://deno.land/std@0.218.2/msgpack/mod.ts'
export * as toml from 'https://deno.land/std@0.218.2/toml/mod.ts'
export * as ulid from 'https://deno.land/std@0.218.2/ulid/mod.ts'
export * as uuid from 'https://deno.land/std@0.218.2/uuid/mod.ts'
export * as yaml from 'https://deno.land/std@0.218.2/yaml/mod.ts'
